name: Build Flutter Desktop
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build windows
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Echo-Music-Windows
          path: build/windows/runner/Release